dist: xenial
language: node_js
node_js: node

cache:
  npm: true

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - setuptools

before_script:
  # - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  # - chmod +x ./cc-test-reporter
  # - './cc-test-reporter before-build'
script:
  # will run `npm ci` automatically here
  - npm run apollo:codegen
  - npm run lint
  # - './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT'
  - npm run build

after_success:
  - pip3 install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - npm run deploy

notifications:
  email: false
